# Generated by Django 5.2.7 on 2025-11-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devID', models.CharField(max_length=50)),
                ('todate', models.CharField(max_length=20)),
                ('totime', models.CharField(max_length=20)),
                ('tmprtr', models.FloatField()),
                ('hmidty', models.FloatField()),
                ('bwsrid', models.CharField(max_length=50)),
                ('pumpid', models.CharField(max_length=20)),
                ('trnsid', models.CharField(max_length=100, unique=True)),
                ('trnamt', models.FloatField()),
                ('trnvol', models.FloatField()),
                ('utpriz', models.FloatField()),
                ('totvol', models.FloatField()),
                ('totamt', models.FloatField()),
                ('pmpsts', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
