# Generated by Django 5.2.7 on 2025-11-08 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_attnid_transaction_pmpid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('super_admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'super_admin',
            },
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('portal_id', models.CharField(max_length=45)),
                ('super_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.superadmin')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
