# Generated by Django 5.2.7 on 2026-02-18 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBarcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100, unique=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriptions', models.CharField(blank=True, max_length=45, null=True)),
                ('valitity', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Asset_barcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bowser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bowser_id', models.CharField(max_length=100)),
                ('bowser_name', models.CharField(max_length=150)),
                ('bowser_description', models.TextField(blank=True, null=True)),
                ('mqtt_id', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bowsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stationary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stationary_id', models.CharField(max_length=100)),
                ('stationary_name', models.CharField(max_length=150)),
                ('stationary_description', models.TextField(blank=True, null=True)),
                ('mqtt_id', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stationaries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tank_id', models.CharField(max_length=100)),
                ('tank_name', models.CharField(max_length=150)),
                ('tank_description', models.TextField(blank=True, null=True)),
                ('mqtt_id', models.CharField(max_length=10, unique=True)),
                ('pump_count', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tanks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100, null=True)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_assignments',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='superadmin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='takid',
            new_name='tankid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='barnum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mobnum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pmpsts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trnsid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
