# Generated by Django 5.2.7 on 2026-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assetbarcode_authtoken_bowser_stationary_tank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stnID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
